### ISSUE TITLE
Leaving system overnight - after unlocking got an exception - have noticed system slowing - possibly Navigator

### ISSUE THREAD

**Issue by jasonjac2** [stevencohn/OneMore#1027]
# Problem to Solve

Sorry in advance for vague issue.....

Anecdotally a few times after leaving machine locked overnight and coming back, my system appears slow in OneNote and I have in the past closed it down and re-opened.  I think it is when the navigator window is up.  I do have a lot of instances of ON open.

I have also noticed the navigator hanging the main UI thread of ON (well, that is my guess), it seems to happen when I have been invoking it a lot.

Today I got:
************* Exception Text **************
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at River.OneMoreAddIn.UI.MoreListView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4614.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
River.OneMoreAddIn
    Assembly Version: 5.8.4.0
    Win32 Version: 5.8.4
    CodeBase: file:///C:/Program%20Files/River/OneMoreAddIn/River.OneMoreAddIn.dll
----------------------------------------
office

about a minute after unlocking.  and Navigator window was visible, but not active.  I literally clicked on the OneNote window. 
There were about 5 - 7 instances open of OneNote.

# To Reproduce

# Expected Behavior

# Screenshots

# Environment (if applicable)
Version 5.8.4 with OneNote 16.0.16227.20280 32 biton 64 bit OS.

# Additional Context
15| SaveToMRU skipping CopyLinkCmd, method not found
22| Running command CopyLinkCommand
19| SaveToMRU skipping CopyLinkCmd, method not found
24| Running command GotoFavoriteCommand
01| Running command GotoFavoriteCommand
07| Running command AboutCommand
16| Running command GotoFavoriteCommand
20| Running command GotoFavoriteCommand
15| Running command GotoFavoriteCommand
24| Running command AboutCommand
20| Running command GotoFavoriteCommand
16| Running command GotoFavoriteCommand
24| Running command GotoFavoriteCommand
01| Running command GotoFavoriteCommand
16| Running command GotoFavoriteCommand
06| Running command GotoFavoriteCommand
03| Running command GotoFavoriteCommand
05| Running command CopyLinkCommand
21| SaveToMRU skipping CopyLinkCmd, method not found
18| Running command GotoFavoriteCommand
06| Running command GotoFavoriteCommand
06| Running command GotoFavoriteCommand
09| Running command GotoFavoriteCommand
24| Running command GotoFavoriteCommand
21| Running command CopyLinkCommand
07| SaveToMRU skipping CopyLinkCmd, method not found
09| Running command GotoFavoriteCommand
03| Running command CopyLinkCommand
18| SaveToMRU skipping CopyLinkCmd, method not found
03| Running command GotoFavoriteCommand
07| Running command GotoFavoriteCommand
01| Running command GotoFavoriteCommand
03| Running command GotoFavoriteCommand
03| Running command CopyLinkCommand
19| SaveToMRU skipping CopyLinkCmd, method not found
16| Running command GotoFavoriteCommand
09| Running command AboutCommand
03| ..Running command UpdateCommand
15| Running command GotoFavoriteCommand
15| Running command GotoFavoriteCommand
21| Running command NavigatorCommand
01| ..Running command GotoFavoriteCommand
09| error navigating
09| System.ArgumentException
Message: Controls created on one thread cannot be parented to a control on a different thread.
Source: System.Windows.Forms
StackTrace:    at System.Windows.Forms.Control.ControlCollection.Add(Control value)
   at River.OneMoreAddIn.UI.MoreListView.RegisterHostedControl(IMoreHostItem subitem, RegistrationEventArgs e)
   at River.OneMoreAddIn.UI.MoreListView.AddHostedItem(String text, Control control)
   at River.OneMoreAddIn.UI.MoreListView.AddHostedItem(Control control)
   at River.OneMoreAddIn.Commands.NavigatorWindow.<>c__DisplayClass23_0.<UpdateViewOnNavigated>b__1(HierarchyInfo record)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at River.OneMoreAddIn.Commands.NavigatorWindow.<UpdateViewOnNavigated>d__23.MoveNext()
TargetSite: [System.Windows.Forms] System.Windows.Forms.Control+ControlCollection::Add()

21| error navigating
21| System.NullReferenceException
Message: Object reference not set to an instance of an object.
Source: River.OneMoreAddIn
StackTrace:    at River.OneMoreAddIn.Commands.NavigatorWindow.TitleChanged(ListView box, Page page)
   at River.OneMoreAddIn.Commands.NavigatorWindow.<UpdateTitles>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at River.OneMoreAddIn.Commands.NavigatorWindow.<LoadPageHeadings>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at River.OneMoreAddIn.Commands.NavigatorWindow.<ShowPageOutline>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at River.OneMoreAddIn.Commands.NavigatorWindow.<UpdateViewOnNavigated>d__23.MoveNext()
TargetSite: [River.OneMoreAddIn] River.OneMoreAddIn.Commands.NavigatorWindow::TitleChanged()

19| error navigating
19| System.ArgumentException
Message: Controls created on one thread cannot be parented to a control on a different thread.
Source: System.Windows.Forms
StackTrace:    at System.Windows.Forms.Control.ControlCollection.Add(Control value)
   at River.OneMoreAddIn.UI.MoreListView.RegisterHostedControl(IMoreHostItem subitem, RegistrationEventArgs e)
   at River.OneMoreAddIn.UI.MoreListView.AddHostedItem(String text, Control control)
   at River.OneMoreAddIn.UI.MoreListView.AddHostedItem(Control control)
   at River.OneMoreAddIn.Commands.NavigatorWindow.<>c__DisplayClass23_0.<UpdateViewOnNavigated>b__1(HierarchyInfo record)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at River.OneMoreAddIn.Commands.NavigatorWindow.<UpdateViewOnNavigated>d__23.MoveNext()
TargetSite: [System.Windows.Forms] System.Windows.Forms.Control+ControlCollection::Add()

18| Running command GotoFavoriteCommand
16| error navigating
16| System.ArgumentException
Message: Controls created on one thread cannot be parented to a control on a different thread.
Source: System.Windows.Forms
StackTrace:    at System.Windows.Forms.Control.ControlCollection.Add(Control value)
   at River.OneMoreAddIn.UI.MoreListView.RegisterHostedControl(IMoreHostItem subitem, RegistrationEventArgs e)
   at River.OneMoreAddIn.UI.MoreListView.AddHostedItem(String text, Control control)
   at River.OneMoreAddIn.UI.MoreListView.AddHostedItem(Control control)
   at River.OneMoreAddIn.Commands.NavigatorWindow.<>c__DisplayClass23_0.<UpdateViewOnNavigated>b__1(HierarchyInfo record)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at River.OneMoreAddIn.Commands.NavigatorWindow.<UpdateViewOnNavigated>d__23.MoveNext()
TargetSite: [System.Windows.Forms] System.Windows.Forms.Control+ControlCollection::Add()

21| error navigating
21| System.NullReferenceException
Message: Object reference not set to an instance of an object.
Source: River.OneMoreAddIn
StackTrace:    at River.OneMoreAddIn.Commands.NavigatorWindow.TitleChanged(ListView box, Page page)
   at River.OneMoreAddIn.Commands.NavigatorWindow.<UpdateTitles>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at River.OneMoreAddIn.Commands.NavigatorWindow.<LoadPageHeadings>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at River.OneMoreAddIn.Commands.NavigatorWindow.<ShowPageOutline>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at River.OneMoreAddIn.Commands.NavigatorWindow.<UpdateViewOnNavigated>d__23.MoveNext()
TargetSite: [River.OneMoreAddIn] River.OneMoreAddIn.Commands.NavigatorWindow::TitleChanged()

01| error navigating
01| System.ArgumentException
Message: Controls created on one thread cannot be parented to a control on a different thread.
Source: System.Windows.Forms
StackTrace:    at System.Windows.Forms.Control.ControlCollection.Add(Control value)
   at River.OneMoreAddIn.UI.MoreListView.RegisterHostedControl(IMoreHostItem subitem, RegistrationEventArgs e)
   at River.OneMoreAddIn.UI.MoreListView.AddHostedItem(String text, Control control)
   at River.OneMoreAddIn.UI.MoreListView.AddHostedItem(Control control)
   at River.OneMoreAddIn.Commands.NavigatorWindow.<>c__DisplayClass23_0.<UpdateViewOnNavigated>b__1(HierarchyInfo record)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at River.OneMoreAddIn.Commands.NavigatorWindow.<UpdateViewOnNavigated>d__23.MoveNext()
TargetSite: [System.Windows.Forms] System.Windows.Forms.Control+ControlCollection::Add()

19| error navigating
19| System.ArgumentException
Message: Controls created on one thread cannot be parented to a control on a different thread.
Source: System.Windows.Forms
StackTrace:    at System.Windows.Forms.Control.ControlCollection.Add(Control value)
   at River.OneMoreAddIn.UI.MoreListView.RegisterHostedControl(IMoreHostItem subitem, RegistrationEventArgs e)
   at River.OneMoreAddIn.UI.MoreListView.AddHostedItem(String text, Control control)
   at River.OneMoreAddIn.UI.MoreListView.AddHostedItem(Control control)
   at River.OneMoreAddIn.Commands.NavigatorWindow.<>c__DisplayClass23_0.<UpdateViewOnNavigated>b__1(HierarchyInfo record)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at River.OneMoreAddIn.Commands.NavigatorWindow.<UpdateViewOnNavigated>d__23.MoveNext()
TargetSite: [System.Windows.Forms] System.Windows.Forms.Control+ControlCollection::Add()

21| error navigating
21| System.NullReferenceException
Message: Object reference not set to an instance of an object.
Source: River.OneMoreAddIn
StackTrace:    at River.OneMoreAddIn.Commands.NavigatorWindow.TitleChanged(ListView box, Page page)
   at River.OneMoreAddIn.Commands.NavigatorWindow.<UpdateTitles>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at River.OneMoreAddIn.Commands.NavigatorWindow.<LoadPageHeadings>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at River.OneMoreAddIn.Commands.NavigatorWindow.<ShowPageOutline>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at River.OneMoreAddIn.Commands.NavigatorWindow.<UpdateViewOnNavigated>d__23.MoveNext()
TargetSite: [River.OneMoreAddIn] River.OneMoreAddIn.Commands.NavigatorWindow::TitleChanged()

22| error navigating
22| System.ArgumentException
Message: Controls created on one thread cannot be parented to a control on a different thread.
Source: System.Windows.Forms
StackTrace:    at System.Windows.Forms.Control.ControlCollection.Add(Control value)
   at River.OneMoreAddIn.UI.MoreListView.RegisterHostedControl(IMoreHostItem subitem, RegistrationEventArgs e)
   at River.OneMoreAddIn.UI.MoreListView.AddHostedItem(String text, Control control)
   at River.OneMoreAddIn.UI.MoreListView.AddHostedItem(Control control)
   at River.OneMoreAddIn.Commands.NavigatorWindow.<>c__DisplayClass23_0.<UpdateViewOnNavigated>b__1(HierarchyInfo record)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at River.OneMoreAddIn.Commands.NavigatorWindow.<UpdateViewOnNavigated>d__23.MoveNext()
TargetSite: [System.Windows.Forms] System.Windows.Forms.Control+ControlCollection::Add()

01| Running command CopyLinkCommand
03| SaveToMRU skipping CopyLinkCmd, method not found
04| Running command GotoFavoriteCommand
16| error navigating
16| System.ArgumentException
Message: Controls created on one thread cannot be parented to a control on a different thread.
Source: System.Windows.Forms
StackTrace:    at System.Windows.Forms.Control.ControlCollection.Add(Control value)
   at River.OneMoreAddIn.UI.MoreListView.RegisterHostedControl(IMoreHostItem subitem, RegistrationEventArgs e)
   at River.OneMoreAddIn.UI.MoreListView.AddHostedItem(String text, Control control)
   at River.OneMoreAddIn.UI.MoreListView.AddHostedItem(Control control)
   at River.OneMoreAddIn.Commands.NavigatorWindow.<>c__DisplayClass23_0.<UpdateViewOnNavigated>b__1(HierarchyInfo record)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at River.OneMoreAddIn.Commands.NavigatorWindow.<UpdateViewOnNavigated>d__23.MoveNext()
TargetSite: [System.Windows.Forms] System.Windows.Forms.Control+ControlCollection::Add()

21| error navigating
21| System.NullReferenceException
Message: Object reference not set to an instance of an object.
Source: River.OneMoreAddIn
StackTrace:    at River.OneMoreAddIn.Commands.NavigatorWindow.TitleChanged(ListView box, Page page)
   at River.OneMoreAddIn.Commands.NavigatorWindow.<UpdateTitles>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at River.OneMoreAddIn.Commands.NavigatorWindow.<LoadPageHeadings>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at River.OneMoreAddIn.Commands.NavigatorWindow.<ShowPageOutline>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at River.OneMoreAddIn.Commands.NavigatorWindow.<UpdateViewOnNavigated>d__23.MoveNext()
TargetSite: [River.OneMoreAddIn] River.OneMoreAddIn.Commands.NavigatorWindow::TitleChanged()

04| error navigating
04| System.ArgumentException
Message: Controls created on one thread cannot be parented to a control on a different thread.
Source: System.Windows.Forms
StackTrace:    at System.Windows.Forms.Control.ControlCollection.Add(Control value)
   at River.OneMoreAddIn.UI.MoreListView.RegisterHostedControl(IMoreHostItem subitem, RegistrationEventArgs e)
   at River.OneMoreAddIn.UI.MoreListView.AddHostedItem(String text, Control control)
   at River.OneMoreAddIn.UI.MoreListView.AddHostedItem(Control control)
   at River.OneMoreAddIn.Commands.NavigatorWindow.<>c__DisplayClass23_0.<UpdateViewOnNavigated>b__1(HierarchyInfo record)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at River.OneMoreAddIn.Commands.NavigatorWindow.<UpdateViewOnNavigated>d__23.MoveNext()
TargetSite: [System.Windows.Forms] System.Windows.Forms.Control+ControlCollection::Add()

15| navigation service exception 0
15| System.Runtime.InteropServices.COMException
Message: Error HRESULT E_FAIL has been returned from a call to a COM component.
Description: Unrecognized error code 0x80004005
ErrorCode: 0x80004005 (-2147467259)
HResult: 0x80004005 (-2147467259)
Source: Microsoft.Office.Interop.OneNote
StackTrace:    at Microsoft.Office.Interop.OneNote.Window.get_CurrentPageId()
   at River.OneMoreAddIn.OneNote.get_CurrentPageId()
   at River.OneMoreAddIn.Commands.NavigationService.<Scan>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at River.OneMoreAddIn.Commands.NavigationService.<<Startup>b__11_0>d.MoveNext()
TargetSite: [Microsoft.Office.Interop.OneNote] Microsoft.Office.Interop.OneNote.Window::get_CurrentPageId()

05| OnBeginShutdown(custom[])
05| ..shutting down UI
05| ..OnDisconnection(RemoveMode:ext_dm_HostShutdown,custom:[])
05| ..disposing 31 streams
05| ..closing log

01| Starting dllhost 45940, 2592 Mhz, 32 MB, en-US/en-US, v5.8.4, OneNote 15.0, Office 16.0, 2023-04-27 09:35
01| ..C:\Program Files (x86)\Microsoft Office\root\Office16\ONENOTE.EXE (16.0.16227.20280)
01| ..OnConnection(ConnectionMode:ext_cm_Startup,custom[1:Int32])
01| ..OneAddInsUpdate(custom[])
01| ..building ribbon
01| ..building ribbon colorizer commands
01| ..building ribbon language proofing commands
01| ..building context menu
01| ..OnStartupComplete(custom[])
01| ..starting command service
01| ..starting reminder service
01| ..starting navigation service
01| ..ready
08| Running command UpdateCommand
03| ..defined 46 hotkeys for input locale 2057
16| OnBeginShutdown(custom[])
16| ..shutting down UI
16| ..OnDisconnection(RemoveMode:ext_dm_HostShutdown,custom:[])
16| ..disposing 5 streams
16| ..closing log

01| Starting dllhost 27788, 2592 Mhz, 32 MB, en-US/en-US, v5.8.4, OneNote 15.0, Office 16.0, 2023-04-27 09:41
01| ..C:\Program Files (x86)\Microsoft Office\Root\Office16\ONENOTE.EXE (16.0.16227.20280)
01| ..OnConnection(ConnectionMode:ext_cm_Startup,custom[1:Int32])
01| ..OneAddInsUpdate(custom[])
01| ..building ribbon
01| ..building ribbon colorizer commands
01| ..building ribbon language proofing commands
01| ..building context menu
01| ..OnStartupComplete(custom[])
01| ..starting command service
01| ..starting reminder service
01| ..starting navigation service
01| ..ready
08| Running command UpdateCommand
03| ..defined 46 hotkeys for input locale 2057
09| Running command GotoFavoriteCommand
09| Running command GotoFavoriteCommand
08| Running command GotoFavoriteCommand
09| Running command AboutCommand

THE FINE PRINT This is a hobby project that I started for myself. I'm happy to take requests and will promise to
consider each one carefully but offer no guarantees that I will ultimately agree to their
usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around
then I will probably reject the request - you've been warned!

**Comment by stevencohn** [comment]
I believe this may be resolved by #1388. Closing this older ticket.
