### ISSUE TITLE
Error adding image caption

### ISSUE THREAD

**Issue by JX3V** [stevencohn/OneMore#1059]
# Problem to Solve

Error message when attempting to add image caption:

`Error running command AddCaptionCommand. See log file for details`

Log file snippet included below.

# To Reproduce

1. Right-click image on OneNote page
2. Select "Add Caption"

# Expected Behavior

Add caption ability.

# Environment (if applicable)

 - OneNote Version: [Microsoft® OneNote® for Microsoft 365 MSO (Version 2306 Build 16.0.16529.20164) 64-bit]
 - OneMore Version [Version 5.8.4 with OneNote 16.0.16626.20078]

# Additional Context

```
19| Running command AddCaptionCommand
19| Error running command AddCaptionCommand
19| System.IO.FileFormatException
Message: The codec cannot use the type of stream provided.
Source: PresentationCore
StackTrace:    at System.Windows.Media.Imaging.BitmapDecoder..ctor(Stream bitmapStream, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, Guid expectedClsId)
   at System.Windows.Media.Imaging.PngBitmapDecoder..ctor(Stream bitmapStream, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption)
   at River.OneMoreAddIn.Commands.PlantUmlHelper.ExtractUmlFromImageData(String imageData)
   at River.OneMoreAddIn.Commands.AddCaptionCommand.<Execute>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at River.OneMoreAddIn.CommandFactory.<Run>d__5.MoveNext()
TargetSite: [PresentationCore] System.Windows.Media.Imaging.BitmapDecoder::.ctor()
```

**Comment by stevenmcohn** [comment]
What type of image did you attach to your page? (.bmp, .gif, .jpg, etc?)

**Comment by stevencohn** [comment]
What type of image did you attach to your page? (.bmp, .gif, .jpg, etc?)
