### ISSUE TITLE
XML parse error on page with extended unicode characters

### ISSUE THREAD

**Issue by DarkStar777** [stevencohn/OneMore#1106]
# Problem to Solve

On a page with extended unicode characters (Nerd Font) I tried to Disable Spell Check (ProofingCommand) and got XML error. It is possible this is a OneNote bug not properly encoding the data.

I verified that removing these characters resolves the issue.

To create a file with the string in question:

```
openssl base64 -d <<'__EOF__' | gunzip > 'encoded-characters.txt'
H4sIAD2a7mQAAxXNPQrCUBAE4N5TzFF1g0WIIHlNHiQoFmpeID9YhBByGg8wW+QC
jsW3C7MwS/uAsYOfNrj18DzAjxVoE6OBTYDGU17yllaSLLKCtyt4P4NJPWnGPrUP
+KUGx1y7UVCpbdCHzPCNpYL/JRTwsj78AM04bi9/AAAA
__EOF__
```

# To Reproduce

1. Insert some Nerd Font characters on a page (likely not limited to Nerd Font)
2. Click on 'Edit > Disable Spell Check'
3. Fragment of error log:

```
Starting dllhost 28920, 1600 Mhz, 64 MB, en-US/en-US, v5.8.5, OneNote 15.0, Office 16.0, 2023-08-29 20:01
01| ..C:\Program Files\Microsoft Office\root\Office16\ONENOTE.EXE (16.0.16626.20170)
...
    10| Running command ProofingCommand
    10| ..error wrapping /<span
    style='font-family:"JetBrainsMono NFM Light"'>  | ­  &#23;               &#985633;    &#984535;  Â </span><span
    style='font-family:"Segoe UI Emoji"'>☑</span><span style='font-family:"JetBrainsMono NFM Light"'> &#986057;   </span>/
    10| Error running command ProofingCommand
    10| System.Xml.XmlException
    Message: '', hexadecimal value 0x17, is an invalid character. Line 2, position 59.
    Source: System.Xml
    StackTrace:    at System.Xml.XmlTextReaderImpl.Throw(Exception e)
       at System.Xml.XmlTextReaderImpl.ParseNumericCharRefInline(Int32 startPos, Boolean expand, StringBuilder internalSubsetBuilder, Int32& charCount, EntityType& entityType)
       at System.Xml.XmlTextReaderImpl.ParseCharRefInline(Int32 startPos, Int32& charCount, EntityType& entityType)
       at System.Xml.XmlTextReaderImpl.ParseText(Int32& startPos, Int32& endPos, Int32& outOrChars)
       at System.Xml.XmlTextReaderImpl.ParseText()
       at System.Xml.XmlTextReaderImpl.ParseElementContent()
       at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
       at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
       at System.Xml.Linq.XElement.ReadElementFrom(XmlReader r, LoadOptions o)
       at System.Xml.Linq.XElement.Load(XmlReader reader, LoadOptions options)
       at System.Xml.Linq.XElement.Parse(String text, LoadOptions options)
       at River.OneMoreAddIn.XCDataExtensions.GetWrapper(XCData cdata)
       at River.OneMoreAddIn.Commands.ProofingCommand.<>c.<Execute>b__2_1(XElement e)
       at River.OneMoreAddIn.IEnumerableExtensions.ForEach[T](IEnumerable`1 collection, Action`1 action)
       at River.OneMoreAddIn.Commands.ProofingCommand.<Execute>d__2.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
       at River.OneMoreAddIn.CommandFactory.<Run>d__5.MoveNext()
    TargetSite: [System.Xml] System.Xml.XmlTextReaderImpl::Throw()
```

# Expected Behavior

Disable Spell Checking on the page or selected text, not throw an error.

# Screenshots

The characters on the page are displayed properly, font is JetBrainsMono NFM Light
![image](https://github.com/stevencohn/OneMore/assets/8376117/220173c7-d901-48ae-afb0-a46e528c6942)

# Environment (if applicable)

 - Windows Version: Windows 11
 - OneNote Version: Office 365, 64bit
 - OneMore Version: 5.8.5

**Comment by stevencohn** [comment]
I'm unable to reproduce with the given instructions. Can you please export the offending page as a OneNote.one file and attach it here?

**Comment by stevencohn** [comment]
Inactive
