### ISSUE TITLE
#Hashtag Search fails

### ISSUE THREAD

**Issue by akadormouse** [stevencohn/OneMore#1220]
# Problem to Solve

Clicking on Search Hastags fails

![image](https://github.com/stevencohn/OneMore/assets/91322324/1d35c4eb-6192-4650-82c4-ff4c4cbdf7a5)

03| Running command HashtagCommand
03| Error running command HashtagCommand
03| System.DllNotFoundException
Message: Unable to load DLL 'SQLite.Interop.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
Source: System.Data.SQLite
StackTrace:    at System.Data.SQLite.UnsafeNativeMethods.sqlite3_open_interop(Byte[] utf8Filename, Byte[] vfsName, SQLiteOpenFlagsEnum flags, Int32 extFuncs, IntPtr& db)
   at System.Data.SQLite.SQLite3.Open(String strFilename, String vfsName, SQLiteConnectionFlags connectionFlags, SQLiteOpenFlagsEnum openFlags, Int32 maxPoolSize, Boolean usePool)
   at System.Data.SQLite.SQLiteConnection.Open()
   at River.OneMoreAddIn.Commands.HashtagProvider..ctor()
   at River.OneMoreAddIn.Commands.HashtagDialog.PopulateTags(Object sender, EventArgs e)
   at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
   at River.OneMoreAddIn.Commands.HashtagDialog..ctor()
   at River.OneMoreAddIn.Commands.HashtagCommand.<Execute>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at River.OneMoreAddIn.CommandFactory.<Run>d__5.MoveNext()
TargetSite: [System.Data.SQLite] System.Data.SQLite.UnsafeNativeMethods::sqlite3_open_interop()

**Comment by emuell1696** [comment]
Same problem here ... on two clients

![OneMore_Hash_Error](https://github.com/stevencohn/OneMore/assets/32419212/cb88bd4b-8543-45bc-bdc2-b69a23ad69fa)
[OneMore.log](https://github.com/stevencohn/OneMore/files/13697669/OneMore.log)

**Comment by stevencohn** [comment]
Is this file on your system?

`C:\Program Files\River3\OneMoreAddIn\x86\SQLite.Interop.dll`

**Comment by akadormouse** [comment]
Yes

**Comment by stevencohn** [comment]
Sorry one more question, are you running 64 bit Office?

**Comment by akadormouse** [comment]
yes. I wondered about the x86 folder

**Comment by stevencohn** [comment]
If you wouldn't mind, please try this patch. If it works, I'll release it. Sorry I have limited machines right now and don't have a 64-bit Office install readily available.

1. Close OneNote
2. Uninstall OneMore
3. Download and install this temp installer

[OneMore_6.0.0_Setupx64.msi.zip](https://github.com/stevencohn/OneMore/files/13698915/OneMore_6.0.0_Setupx64.msi.zip)

**Comment by emuell1696** [comment]
Hi, the patched version works here on my side.

Thanks

**Comment by stevencohn** [comment]
> Works for me too. Requires ##tag rather than #tag but I assume that's by design.

As is documented on [onemoreaddin.com](https://onemoreaddin.com/commands/Search%20and%20Tag%20Commands.htm).
