### ISSUE TITLE
Calendar insertion not working

### ISSUE THREAD

**Issue by osman1963** [stevencohn/OneMore#150]
When trying to insert a calendar for this month (Jan 2021) it gives me an error message. However, if I try to insert a calendar for a previous month, it works fine. This wasn't the case previously. Few versions ago it worked just fine.
Here is the log file for this error

19984:8] Log restarted
19984:8] Running command InsertCalendarCommand
19984:8] Error running command InsertCalendarCommand
19984:8] System.ArgumentOutOfRangeException
Message: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
Source: mscorlib
StackTrace:    at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at System.Linq.Enumerable.ElementAt[TSource](IEnumerable`1 source, Int32 index)
   at River.OneMoreAddIn.Commands.InsertCalendarCommand.MakeCalendar(Int32 year, Int32 month, Boolean large)
   at River.OneMoreAddIn.Commands.InsertCalendarCommand.<Execute>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at River.OneMoreAddIn.CommandFactory.<Run>d__5`1.MoveNext()
TargetSite: [mscorlib] System.ThrowHelper::ThrowArgumentOutOfRangeException()

19984:8] Running command AboutCommand

Thanks in advance for your help, and of course Thanks soooo much for this awsome add-in

**Comment by G2G2G** [comment]
Have the same issue. It seems any month can be added except current. Thank you for the great addin !

**Comment by stevencohn** [comment]
Fixed here https://github.com/stevencohn/OneMore/releases/tag/3.12.2

**Comment by osman1963** [comment]
Thanks a million :)
