### ISSUE TITLE
ScanHashtagsCommand - Exception

### ISSUE THREAD

**Issue by nhwCoder** [stevencohn/OneMore#1683]
# Problem to Solve

ScanHashtagsCommand [Ctrl+ALt+F9] results in Exception (see log below)

# To Reproduce

1. Add a link
   - Address: C:\
   - Text: Link ##Test ##Test
1. Use keytip [Ctrl+ALt+F9] ScanHashtagsCommand
1. See error below

# Environment (if applicable)

 - OneMore Version 6.6.1
 - OneNote 16.0.18129.20158

# The Exception

07|02:14:22.682| Running command ScanHashtagsCommand
07|02:14:23.687| Error running command ScanHashtagsCommand
07|02:14:23.687| System.ArgumentOutOfRangeException
Message: Der Index und die Länge müssen sich auf eine Position in der Zeichenfolge beziehen.
=====> (+/-)EN:  "The index and length must refer to a location within the string."
Parametername: length
Source: mscorlib
StackTrace:    bei System.String.Substring(Int32 startIndex, Int32 length)
   bei River.OneMoreAddIn.Commands.TextAtom.Replace(Int32 index, Int32 length, XElement replacement)
   bei River.OneMoreAddIn.Commands.ElementAtom.Replace(Int32 index, Int32 length, XElement replacement)
   bei River.OneMoreAddIn.Commands.SearchAndReplaceEditor.Replace(XElement wrapper, Int32 searchIndex, Int32 searchLength, String stringValue, XElement elementValue)
   bei River.OneMoreAddIn.Commands.SearchAndReplaceEditor.ScanElement(XElement element)
   bei River.OneMoreAddIn.Commands.SearchAndReplaceEditor.SearchAndReplace(XElement paragraph)
   bei River.OneMoreAddIn.Commands.HashtagPageScanner.Scan()
   bei River.OneMoreAddIn.Commands.HashtagScanner.<ScanPage>d__21.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   bei River.OneMoreAddIn.Commands.HashtagScanner.<Scan>d__20.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   bei River.OneMoreAddIn.Commands.HashtagScanner.<Scan>d__19.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei River.OneMoreAddIn.Commands.HashtagScanner.<Scan>d__19.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   bei River.OneMoreAddIn.Commands.ScanHashtagsCommand.<Execute>d__1.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   bei River.OneMoreAddIn.CommandFactory.<Run>d__6.MoveNext()
TargetSite: [mscorlib] System.String::Substring()

**Comment by nhwCoder** [comment]
Here are the pictures
![image](https://github.com/user-attachments/assets/41455ca7-8ab7-433e-8d9b-9b2b1068f970)

Before
![image](https://github.com/user-attachments/assets/dd17dc87-5354-45cd-8945-9b9eea3d02b7)

**Comment by stevencohn** [comment]
I cannot replicate this with your instructions. It seems to work fine. I don't see any exceptions.

![image](https://github.com/user-attachments/assets/7c2e7a98-2702-40de-b88d-fa5ce78f37c2)

**Comment by stevencohn** [comment]
Note to self: The `Ctrl+Alt+F9` request is not the problem, but rather the subsequent automated scanner that then doesn't recognize the highlighted tag. A more complete stack trace:

```
03|08:07:24.737| hashtag service exception 4
System.ArgumentOutOfRangeException
Message: Index and length must refer to a location within the string.
Parameter name: length
Source: mscorlib
StackTrace:    at System.String.Substring(Int32 startIndex, Int32 length)
   at River.OneMoreAddIn.Commands.TextAtom.Replace(Int32 index, Int32 length, XElement replacement) in C:\Github\OneMore\OneMore\Commands\Search\Atoms\TextAtom.cs:line 58
   at River.OneMoreAddIn.Commands.ElementAtom.Replace(Int32 index, Int32 length, XElement replacement) in C:\Github\OneMore\OneMore\Commands\Search\Atoms\ElementAtom.cs:line 61
   at River.OneMoreAddIn.Commands.SearchAndReplaceEditor.Replace(XElement wrapper, Int32 searchIndex, Int32 searchLength, String stringValue, XElement elementValue) in C:\Github\OneMore\OneMore\Commands\Search\SearchAndReplaceEditor.cs:line 300
   at River.OneMoreAddIn.Commands.SearchAndReplaceEditor.ScanElement(XElement element) in C:\Github\OneMore\OneMore\Commands\Search\SearchAndReplaceEditor.cs:line 208
   at River.OneMoreAddIn.Commands.SearchAndReplaceEditor.SearchAndReplace(XElement paragraph) in C:\Github\OneMore\OneMore\Commands\Search\SearchAndReplaceEditor.cs:line 120
   at River.OneMoreAddIn.Commands.HashtagPageScanner.Scan() in C:\Github\OneMore\OneMore\Commands\Tagging\HashtagPageScanner.cs:line 116
   at River.OneMoreAddIn.Commands.HashtagScanner.<ScanPage>d__21.MoveNext() in C:\Github\OneMore\OneMore\Commands\Tagging\HashtagScanner.cs:line 379
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at River.OneMoreAddIn.Commands.HashtagScanner.<Scan>d__20.MoveNext() in C:\Github\OneMore\OneMore\Commands\Tagging\HashtagScanner.cs:line 299
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at River.OneMoreAddIn.Commands.HashtagScanner.<Scan>d__19.MoveNext() in C:\Github\OneMore\OneMore\Commands\Tagging\HashtagScanner.cs:line 229
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at River.OneMoreAddIn.Commands.HashtagScanner.<Scan>d__19.MoveNext() in C:\Github\OneMore\OneMore\Commands\Tagging\HashtagScanner.cs:line 251
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at River.OneMoreAddIn.Commands.HashtagService.<Scan>d__21.MoveNext() in C:\Github\OneMore\OneMore\Commands\Tagging\HashtagService.cs:line 216
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at River.OneMoreAddIn.Commands.HashtagService.<StartupLoop>d__19.MoveNext() in C:\Github\OneMore\OneMore\Commands\Tagging\HashtagService.cs:line 126
TargetSite: [mscorlib] System.String::Substring()

03|08:07:24.737| hashtag service has stopped; check for exceptions above
```
