### ISSUE TITLE
Show storage space occupied by each page?

### ISSUE THREAD

**Issue by andyylin** [stevencohn/OneMore#248]
Some of my sections are huge, based on the size of the backup .one file. But it's hard to determine what exactly is taking up space (usually photos since they're inserted into OneNote at full resolution).

Is it possible to analyze a OneNote section and determine which pages or even elements are taking up space?

At the moment, I can only go one by one through each photo and either use OneMore's Resize feature to check the resolution and file size, or else use OneNote's built in "Restore to original size" to check if the image is too large.

Maybe a possible output is a new page with a list of the pages in the section and the storage space occupied by each page.

**Comment by andyylin** [comment]
Saw the release, thanks for this.

Seems to have a bug: I don't have backups set up but I ran this with check backups enabled, and it threw me an error.

![image](https://user-images.githubusercontent.com/51783311/130004489-ee44bff0-780a-4884-a3c8-0702de65a56c.jpeg)

Here are the log contents:

```

9920:9] Running command AnalyzeCommand
9920:9] Error running command AnalyzeCommand
9920:9] System.IO.DirectoryNotFoundException
Message: Could not find a part of the path 'C:\Users\XXX\AppData\Local\Microsoft\OneNote\16.0\Backup\Personal (Web)'.
Source: mscorlib
StackTrace:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.EnumerateFiles(String path, String searchPattern)
   at River.OneMoreAddIn.Commands.AnalyzeCommand.ReportSections(Table table, XElement folder, String folderPath)
   at River.OneMoreAddIn.Commands.AnalyzeCommand.ReportSections(XElement container, XElement notebooks)
   at River.OneMoreAddIn.Commands.AnalyzeCommand.<Execute>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at River.OneMoreAddIn.CommandFactory.<Run>d__6.MoveNext()
TargetSite: [mscorlib] System.IO.__Error::WinIOError()

```

**Comment by stevencohn** [comment]
Fix 3.29.1 released

**Comment by andyylin** [comment]
The macro runs and finishes now. The result page looks quite nice!

However, I'm seeing an issue where the Section summary is formatted but doesn't show data. Attaching an example screenshot.

![image](https://user-images.githubusercontent.com/51783311/130541153-b5b671eb-b8ab-4bff-9584-c7452aef86a5.jpeg)

**Comment by stevencohn** [comment]
As mentioned in the Wiki, this relies on at least one local backup to be previously run. If those backup files do not exist then this table will be blank. You can manually run a backup from the OneNote Options dialog. Under _Save and Backup_ click _Backup all notebooks now_.

**Comment by andyylin** [comment]
> As mentioned in the Wiki, this relies on at least one local backup to be previously run. If those backup files do not exist then this table will be blank. You can manually run a backup from the OneNote Options dialog. Under _Save and Backup_ click _Backup all notebooks now_. 

Backups are enabled and it looks like the Summary calculates things just fine.

![image](https://user-images.githubusercontent.com/51783311/130599568-cb8487ac-114f-4d54-8944-d46a47232c88.jpeg)

It's the Sections part that is showing up empty.

Is it maybe because of the Chinese characters in the file system? I tried to click the generated link to the backup folder and got an error. Manually navigating to the backup folder works fine.

![image](https://user-images.githubusercontent.com/51783311/130599494-eecb9abf-3748-4dfd-b0ff-735a54148b72.jpeg)

![image](https://user-images.githubusercontent.com/51783311/130599523-f93b27bd-0d79-46db-a5f4-ca80bba1111c.jpeg)

**Comment by stevencohn** [comment]
It's possible it's the Chinese characters. I'll see if I can emulate that on my English machine (it's impossible for me to debug this on a Chinese machine, sorry I don't read Chinese!)

**Comment by andyylin** [comment]
Any hope of getting this fixed? Perhaps there's someone with more coding knowledge and a Chinese machine that can help?
