### ISSUE TITLE
Error with Snippets and Tables

### ISSUE THREAD

**Issue by NoralK** [stevencohn/OneMore#357]
**Describe the bug**
When a Notebook has a password Snippets and Table are either grayed out or if you use a hotkey like Alt-Shift-F11 it gives "error running command...".  Below is the log.

**Environment **
 - OneNote Version: 15.0 32-bit

**Additional context**
```

16368:1] Starting dllhost 16368, CPU=2401Mhz, en-US/en-US, v4.11, OneNote 15.0, Office 16.0
16368:1] ..OnConnection(ConnectionMode:ext_cm_Startup,1)
16368:1] ..OneAddInsUpdate(custom[]:0)
16368:1] ..building ribbon
16368:1] ..building ribbon colorizer commands
16368:1] ..RibbonLoaded()
16368:1] ..OnStartupComplete(custom[]:0)
16368:1] ..OneNote backup folder:: C:\Users\Noral\AppData\Local\Microsoft\OneNote\16.0\Backup
16368:1] ..OneNote default folder: C:\Users\Noral\Documents\OneNote Notebooks
16368:1] ..OneNote unfiled folder: C:\Users\Noral\Documents\OneNote Notebooks\Quick Notes.one
16368:1] ..OneNote process module: C:\Program Files (x86)\Microsoft Office\root\Office16\ONENOTE.EXE (16.0.14701.20226)
16368:1] ..defining hotkeys for input locale 1033
16368:1] ..ready
16368:1] error getting page {AB355BCA-8BC2-4129-8194-7CB29D7EE5A6}{1}{E1948665010471475383211884402144634003011015}
16368:1] System.Runtime.InteropServices.COMException
Message: Exception from HRESULT: 0x8004201B
Description: The section is encrypted and locked
ErrorCode: 0x8004201B (-2147213285)
HResult: 0x8004201B (-2147213285)
Source: River.OneMoreAddIn
StackTrace:    at Microsoft.Office.Interop.OneNote.IApplication.GetPageContent(String bstrPageID, String& pbstrPageXmlOut, PageInfo pageInfoToExport, XMLSchema xsSchema)
   at River.OneMoreAddIn.OneNote.GetPage(String pageId, PageDetail detail)
TargetSite: [River.OneMoreAddIn] Microsoft.Office.Interop.OneNote.IApplication::GetPageContent()

16368:1] Running command InsertLineCommand
16368:1] Running command InsertLineCommand
16368:1] ..error getting page {AB355BCA-8BC2-4129-8194-7CB29D7EE5A6}{1}{E1948665010471475383211884402144634003011015}
16368:1] ..System.Runtime.InteropServices.COMException
Message: Exception from HRESULT: 0x8004201B
Description: The section is encrypted and locked
ErrorCode: 0x8004201B (-2147213285)
HResult: 0x8004201B (-2147213285)
Source: River.OneMoreAddIn
StackTrace:    at Microsoft.Office.Interop.OneNote.IApplication.GetPageContent(String bstrPageID, String& pbstrPageXmlOut, PageInfo pageInfoToExport, XMLSchema xsSchema)
   at River.OneMoreAddIn.OneNote.GetPage(String pageId, PageDetail detail)
TargetSite: [River.OneMoreAddIn] Microsoft.Office.Interop.OneNote.IApplication::GetPageContent()

16368:1] Error running command InsertLineCommand
16368:1] System.NullReferenceException
Message: Object reference not set to an instance of an object.
Source: River.OneMoreAddIn
StackTrace:    at River.OneMoreAddIn.OneNote..ctor(Page& page, XNamespace& ns, PageDetail detail)
   at River.OneMoreAddIn.Commands.InsertLineCommand.<Execute>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at River.OneMoreAddIn.CommandFactory.<Run>d__6.MoveNext()
TargetSite: [River.OneMoreAddIn] River.OneMoreAddIn.OneNote::.ctor()
```

**Comment by stevencohn** [comment]
So there's a couple of things going on here. First, the OneMore menu tries to enable some commands and submenus based on the current context. If you're not currently focused on the content of a page, Snippets and Tables are disabled. But additionally, the menu doesn't initialize the very first time you open; if you open it again, it figures out the context and enables/disables items correctly.

Second, if you press Alt+Shift+F11 (insert horizontal line) and the current section is locked, yes, you will get that error message. This should be fixed so it gracefully displays a friendly message instead. That I can fix.

Note if a password-protected section is not locked, commands should still complete successfully. If that's not the case then let me know.

**Comment by NoralK** [comment]
Thank you for getting back to me.  For the first, it does not - When I first open OneNote I move between Notebooks, that are unlocked, and the menu items are still grayed out.  As for the second ... I have tried the hotkey and it produces the same issue.

**Comment by stevencohn** [comment]
Seems that OneNote has either changed the sequence in which certain APIs are invoked, APIs that OneMore relies on, or these APIs were just more non-deterministic than I had first presumed. Either way, I think I have a solution and it will be in the next release.
