### ISSUE TITLE
Where can I download webview2Loader.dll from ? It is required for bulk import but OneMore can't find it

### ISSUE THREAD

**Issue by 1001QAdotNET** [stevencohn/OneMore#502]
I was trying to test https://github.com/stevencohn/OneMore/issues/300
As indicated there the above dll is missing from my computer
Where can I download this from ?

**Comment by stevencohn** [comment]
The URL that OneMore's installer uses is https://go.microsoft.com/fwlink/p/?LinkId=2124703

This is primarily for Windows 10 since Edge is the default browser in Windows 11 and includes WebView2 which cannot be uninstalled

**Comment by stevencohn** [comment]
Is this a bug or just research?

**Comment by 1001QAdotNET** [comment]
It is a bug. I received an error saying it could not find the dll when I tried to use the bulk import feature

**Comment by 1001QAdotNET** [comment]
Actually that was wrong, here is where the message is showing up saying it can't load the dll

36528:6] ..importing subpage https://automatetheboringstuff.com/2e/chapter4/
36528:7] ..Unable to load DLL 'WebView2Loader.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
36528:7] ..System.DllNotFoundException
Message: Unable to load DLL 'WebView2Loader.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
Source: Microsoft.Web.WebView2.Core
StackTrace:    at Microsoft.Web.WebView2.Core.CoreWebView2Environment.CreateCoreWebView2EnvironmentWithOptions(String browserExecutableFolder, String userDataFolder, ICoreWebView2EnvironmentOptions options, ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler environment_created_handler)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at River.OneMoreAddIn.UI.WebViewWorkerDialog.<StartWorkLoaded>d__4.MoveNext()
TargetSite: [Microsoft.Web.WebView2.Core] Microsoft.Web.WebView2.Core.CoreWebView2Environment::CreateCoreWebView2EnvironmentWithOptions()

36528:13] ..Replaying command CrawlWebPageCommand
36528:6] importing subpage https://automatetheboringstuff.com/2e/chapter3/
36528:1] Unable to load DLL 'WebView2Loader.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
36528:1] System.DllNotFoundException
Message: Unable to load DLL 'WebView2Loader.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
Source: Microsoft.Web.WebView2.Core
StackTrace:    at Microsoft.Web.WebView2.Core.CoreWebView2Environment.CreateCoreWebView2EnvironmentWithOptions(String browserExecutableFolder, String userDataFolder, ICoreWebView2EnvironmentOptions options, ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler environment_created_handler)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at River.OneMoreAddIn.UI.WebViewWorkerDialog.<StartWorkLoaded>d__4.MoveNext()
TargetSite: [Microsoft.Web.WebView2.Core] Microsoft.Web.WebView2.Core.CoreWebView2Environment::CreateCoreWebView2EnvironmentWithOptions()

36528:12] Running command CrawlWebPageCommand
36528:11] ..importing subpage https://osf.io/u8aqv/download/?format=pdf
36528:5] ..Unable to load DLL 'WebView2Loader.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
36528:5] ..System.DllNotFoundException
Message: Unable to load DLL 'WebView2Loader.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
Source: Microsoft.Web.WebView2.Core
StackTrace:    at Microsoft.Web.WebView2.Core.CoreWebView2Environment.CreateCoreWebView2EnvironmentWithOptions(String browserExecutableFolder, String userDataFolder, ICoreWebView2EnvironmentOptions options, ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler environment_created_handler)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at River.OneMoreAddIn.UI.WebViewWorkerDialog.<StartWorkLoaded>d__4.MoveNext()
TargetSite: [Microsoft.Web.WebView2.Core] Microsoft.Web.WebView2.Core.CoreWebView2Environment::CreateCoreWebView2EnvironmentWithOptions()

36528:12] ..Running command CrawlWebPageCommand
36528:3] importing subpage https://archive.org/details/texts
36528:14] Unable to load DLL 'WebView2Loader.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
36528:14] System.DllNotFoundException
Message: Unable to load DLL 'WebView2Loader.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
Source: Microsoft.Web.WebView2.Core
StackTrace:    at Microsoft.Web.WebView2.Core.CoreWebView2Environment.CreateCoreWebView2EnvironmentWithOptions(String browserExecutableFolder, String userDataFolder, ICoreWebView2EnvironmentOptions options, ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler environment_created_handler)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at River.OneMoreAddIn.UI.WebViewWorkerDialog.<StartWorkLoaded>d__4.MoveNext()
TargetSite: [Microsoft.Web.WebView2.Core] Microsoft.Web.WebView2.Core.CoreWebView2Environment::CreateCoreWebView2EnvironmentWithOptions()

36528:7] retrieved 0 bytes from  (https://automatetheboringstuff.com/2e/chapter4/)
36528:7] web page returned empty content
36528:7] importing subpage https://automatetheboringstuff.com/2e/chapter3/
36528:14] retrieved 0 bytes from  (https://archive.org/details/texts)
36528:14] web page returned empty content
36528:14] importing subpage https://archive.org/details/texts
36528:5] retrieved 0 bytes from  (https://osf.io/u8aqv/download/?format=pdf)
36528:1] retrieved 0 bytes from  (https://automatetheboringstuff.com/2e/chapter3/)
36528:1] web page returned empty content
36528:1] importing subpage https://automatetheboringstuff.com/2e/chapter2/
36528:1] importing subpage https://automatetheboringstuff.com/2e/chapter2/

36528:5] web page returned empty content
36528:5] importing subpage https://archive.org/details/texts
36528:15] Unable to load DLL 'WebView2Loader.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
36528:15] System.DllNotFoundException
Message: Unable to load DLL 'WebView2Loader.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
Source: Microsoft.Web.WebView2.Core
StackTrace:    at Microsoft.Web.WebView2.Core.CoreWebView2Environment.CreateCoreWebView2EnvironmentWithOptions(String browserExecutableFolder, String userDataFolder, ICoreWebView2EnvironmentOptions options, ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler environment_created_handler)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at River.OneMoreAddIn.UI.WebViewWorkerDialog.<StartWorkLoaded>d__4.MoveNext()
TargetSite: [Microsoft.Web.WebView2.Core] Microsoft.Web.WebView2.Core.CoreWebView2Environment::CreateCoreWebView2EnvironmentWithOptions()

36528:17] Unable to load DLL 'WebView2Loader.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
36528:17] System.DllNotFoundException
Message: Unable to load DLL 'WebView2Loader.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
Source: Microsoft.Web.WebView2.Core
StackTrace:    at Microsoft.Web.WebView2.Core.CoreWebView2Environment.CreateCoreWebView2EnvironmentWithOptions(String browserExecutableFolder, String userDataFolder, ICoreWebView2EnvironmentOptions options, ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler environment_created_handler)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at River.OneMoreAddIn.UI.WebViewWorkerDialog.<StartWorkLoaded>d__4.MoveNext()
TargetSite: [Microsoft.Web.WebView2.Core] Microsoft.Web.WebView2.Core.CoreWebView2Environment::CreateCoreWebView2EnvironmentWithOptions()

36528:16] Unable to load DLL 'WebView2Loader.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
36528:16] System.DllNotFoundException
Message: Unable to load DLL 'WebView2Loader.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
Source: Microsoft.Web.WebView2.Core
StackTrace:    at Microsoft.Web.WebView2.Core.CoreWebView2Environment.CreateCoreWebView2EnvironmentWithOptions(String browserExecutableFolder, String userDataFolder, ICoreWebView2EnvironmentOptions options, ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler environment_created_handler)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at River.OneMoreAddIn.UI.WebViewWorkerDialog.<StartWorkLoaded>d__4.MoveNext()
TargetSite: [Microsoft.Web.WebView2.Core] Microsoft.Web.WebView2.Core.CoreWebView2Environment::CreateCoreWebView2EnvironmentWithOptions()

36528:18] Unable to load DLL 'WebView2Loader.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
36528:18] System.DllNotFoundException
Message: Unable to load DLL 'WebView2Loader.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
Source: Microsoft.Web.WebView2.Core
StackTrace:    at Microsoft.Web.WebView2.Core.CoreWebView2Environment.CreateCoreWebView2EnvironmentWithOptions(String browserExecutableFolder, String userDataFolder, ICoreWebView2EnvironmentOptions options, ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler environment_created_handler)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at River.OneMoreAddIn.UI.WebViewWorkerDialog.<StartWorkLoaded>d__4.MoveNext()
TargetSite: [Microsoft.Web.WebView2.Core] Microsoft.Web.WebView2.Core.CoreWebView2Environment::CreateCoreWebView2EnvironmentWithOptions()

36528:17] retrieved 0 bytes from  (https://automatetheboringstuff.com/2e/chapter2/)
36528:17] web page returned empty content
36528:17] importing subpage https://automatetheboringstuff.com/2e/chapter1/
36528:16] retrieved 0 bytes from  (https://archive.org/details/texts)
36528:16] web page returned empty content
36528:16] progress dialog completed
36528:15] retrieved 0 bytes from  (https://automatetheboringstuff.com/2e/chapter3/)
36528:15] web page returned empty content
36528:15] importing subpage https://automatetheboringstuff.com/2e/chapter2/
36528:18] retrieved 0 bytes from  (https://archive.org/details/texts)
36528:18] web page returned empty content
36528:18] importing subpage https://archive.org/details/texts
36528:20] Unable to load DLL 'WebView2Loader.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
36528:20] System.DllNotFoundException
Message: Unable to load DLL 'WebView2Loader.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
Source: Microsoft.Web.WebView2.Core
StackTrace:    at Microsoft.Web.WebView2.Core.CoreWebView2Environment.CreateCoreWebView2EnvironmentWithOptions(String browserExecutableFolder, String userDataFolder, ICoreWebView2EnvironmentOptions options, ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler environment_created_handler)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at River.OneMoreAddIn.UI.WebViewWorkerDialog.<StartWorkLoaded>d__4.MoveNext()
TargetSite: [Microsoft.Web.WebView2.Core] Microsoft.Web.WebView2.Core.CoreWebView2Environment::CreateCoreWebView2EnvironmentWithOptions()

36528:21] Unable to load DLL 'WebView2Loader.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
36528:21] System.DllNotFoundException
Message: Unable to load DLL 'WebView2Loader.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
Source: Microsoft.Web.WebView2.Core
StackTrace:    at Microsoft.Web.WebView2.Core.CoreWebView2Environment.CreateCoreWebView2EnvironmentWithOptions(String browserExecutableFolder, String userDataFolder, ICoreWebView2EnvironmentOptions options, ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler environment_created_handler)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at River.OneMoreAddIn.UI.WebViewWorkerDialog.<StartWorkLoaded>d__4.MoveNext()
TargetSite: [Microsoft.Web.WebView2.Core] Microsoft.Web.WebView2.Core.CoreWebView2Environment::CreateCoreWebView2EnvironmentWithOptions()

36528:19] Unable to load DLL 'WebView2Loader.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
36528:19] System.DllNotFoundException
Message: Unable to load DLL 'WebView2Loader.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
Source: Microsoft.Web.WebView2.Core
StackTrace:    at Microsoft.Web.WebView2.Core.CoreWebView2Environment.CreateCoreWebView2EnvironmentWithOptions(String browserExecutableFolder, String userDataFolder, ICoreWebView2EnvironmentOptions options, ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler environment_created_handler)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at River.OneMoreAddIn.UI.WebViewWorkerDialog.<StartWorkLoaded>d__4.MoveNext()
TargetSite: [Microsoft.Web.WebView2.Core] Microsoft.Web.WebView2.Core.CoreWebView2Environment::CreateCoreWebView2EnvironmentWithOptions()

36528:20] retrieved 0 bytes from  (https://automatetheboringstuff.com/2e/chapter2/)
36528:20] web page returned empty content
36528:20] importing subpage https://automatetheboringstuff.com/2e/chapter1/
36528:22] Unable to load DLL 'WebView2Loader.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
36528:22] System.DllNotFoundException
Message: Unable to load DLL 'WebView2Loader.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
Source: Microsoft.Web.WebView2.Core
StackTrace:    at Microsoft.Web.WebView2.Core.CoreWebView2Environment.CreateCoreWebView2EnvironmentWithOptions(String browserExecutableFolder, String userDataFolder, ICoreWebView2EnvironmentOptions options, ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler environment_created_handler)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at River.OneMoreAddIn.UI.WebViewWorkerDialog.<StartWorkLoaded>d__4.MoveNext()
TargetSite: [Microsoft.Web.WebView2.Core] Microsoft.Web.WebView2.Core.CoreWebView2Environment::CreateCoreWebView2EnvironmentWithOptions()

36528:21] retrieved 0 bytes from  (https://archive.org/details/texts)
36528:21] web page returned empty content
36528:21] progress dialog completed
36528:19] retrieved 0 bytes from  (https://automatetheboringstuff.com/2e/chapter1/)
36528:19] web page returned empty content
36528:19] importing subpage https://automatetheboringstuff.com/2e/chapter0/
36528:23] Unable to load DLL 'WebView2Loader.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
36528:23] System.DllNotFoundException
Message: Unable to load DLL 'WebView2Loader.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
Source: Microsoft.Web.WebView2.Core
StackTrace:    at Microsoft.Web.WebView2.Core.CoreWebView2Environment.CreateCoreWebView2EnvironmentWithOptions(String browserExecutableFolder, String userDataFolder, ICoreWebView2EnvironmentOptions options, ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler environment_created_handler)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at River.OneMoreAddIn.UI.WebViewWorkerDialog.<StartWorkLoaded>d__4.MoveNext()
TargetSite: [Microsoft.Web.WebView2.Core] Microsoft.Web.WebView2.Core.CoreWebView2Environment::CreateCoreWebView2EnvironmentWithOptions()

36528:22] retrieved 0 bytes from  (https://automatetheboringstuff.com/2e/chapter1/)
36528:22] web page returned empty content
36528:22] importing subpage https://automatetheboringstuff.com/2e/chapter0/
36528:24] Unable to load DLL 'WebView2Loader.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
36528:24] System.DllNotFoundException
Message: Unable to load DLL 'WebView2Loader.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
Source: Microsoft.Web.WebView2.Core
StackTrace:    at Microsoft.Web.WebView2.Core.CoreWebView2Environment.CreateCoreWebView2EnvironmentWithOptions(String browserExecutableFolder, String userDataFolder, ICoreWebView2EnvironmentOptions options, ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler environment_created_handler)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at River.OneMoreAddIn.UI.WebViewWorkerDialog.<StartWorkLoaded>d__4.MoveNext()
TargetSite: [Microsoft.Web.WebView2.Core] Microsoft.Web.WebView2.Core.CoreWebView2Environment::CreateCoreWebView2EnvironmentWithOptions()

36528:23] retrieved 0 bytes from  (https://automatetheboringstuff.com/2e/chapter0/)
36528:23] web page returned empty content
36528:23] progress dialog completed
36528:24] retrieved 0 bytes from  (https://automatetheboringstuff.com/2e/chapter0/)
36528:24] web page returned empty content
36528:24] progress dialog completed
36528:25] Running command CrawlWebPageCommand
36528:24] ..importing subpage https://automatetheboringstuff.com/2e/chapter3/
36528:22] ..Unable to load DLL 'WebView2Loader.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
36528:22] ..System.DllNotFoundException
Message: Unable to load DLL 'WebView2Loader.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
Source: Microsoft.Web.WebView2.Core
StackTrace:    at Microsoft.Web.WebView2.Core.CoreWebView2Environment.CreateCoreWebView2EnvironmentWithOptions(String browserExecutableFolder, String userDataFolder, ICoreWebView2EnvironmentOptions options, ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler environment_created_handler)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at River.OneMoreAddIn.UI.WebViewWorkerDialog.<StartWorkLoaded>d__4.MoveNext()
TargetSite: [Microsoft.Web.WebView2.Core] Microsoft.Web.WebView2.Core.CoreWebView2Environment::CreateCoreWebView2EnvironmentWithOptions()

36528:13] ..Running command AboutCommand

**Comment by stevencohn** [comment]
I can't repro the error but I may have a solution. The OneMore installer does not include webview2loader.dll but the WebView2 docs suggest that you should. So I'll spin a new installer that does just that and we'll see...

**Comment by stevencohn** [comment]
If you have a chance to try, otherwise it will be in the next official release...

https://github.com/stevencohn/OneMore/releases/tag/4.18.1

**Comment by 1001QAdotNET** [comment]
Working like a charm! Thanks for fixing this!

**Comment by 1001QAdotNET** [comment]
I will continue to test the feature in the coming days
I will open a related improvement issue to see if what I am seeing can be done
