### ISSUE TITLE
Search and Replace Does Not Handle Special Characters Well (seems to force regex)

### ISSUE THREAD

**Issue by megamorphg** [stevencohn/OneMore#562]
**Describe the bug**
When I search and replace including special characters it seems to bug out.
It is very hard to predict what happens when special characters (\/.|-+) are used--it seems to be using regex automatically sometimes and other times not for either the search or replace.

**To Reproduce**
1. Create a page with the character "+:"
2. Perform Find & Replace for replacing "+:" with "+>:". Leave regex unchecked.
3. See error

**Expected behavior**
Find and replace without regex checked should be able to handle any special characters without regex.

**Screenshots**

**Environment (if applicable):**
 - OneNote Version: OneNote 15.0
 - OneMore Version 4.18

**Additional context**
Add any other context about the problem here. Attach page XML file or the app log file as appropriate. You can find the log file here: %localappdata%\temp\OneMore.log

73916:1] Starting dllhost 73916, CPU=3700Mhz, en-US/en-US, v4.18, OneNote 15.0, Office 16.0
73916:1] ..C:\Program Files\Microsoft Office\root\Office16\ONENOTE.EXE (16.0.15427.20210)
73916:1] ..OnConnection(ConnectionMode:ext_cm_Startup,custom[1:Int32])
73916:1] ..OneAddInsUpdate(custom[])
73916:1] ..building ribbon
73916:1] ..building ribbon colorizer commands
73916:1] ..building ribbon language proofing commands
73916:1] ..OnStartupComplete(custom[])
73916:1] ..starting command service
73916:1] ..starting reminder service
73916:1] ..defining hotkeys for input locale 1033
73916:1] ..ready
73916:1] Running command SearchAndReplaceCommand
73916:7] Running command SearchAndReplaceCommand
73916:7] Error running command SearchAndReplaceCommand
73916:7] System.ArgumentException
Message: parsing "+:" - Quantifier {x,y} following nothing.
Source: System
StackTrace:    at System.Text.RegularExpressions.RegexParser.ScanRegex()
   at System.Text.RegularExpressions.RegexParser.Parse(String re, RegexOptions op)
   at System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options, TimeSpan matchTimeout, Boolean useCache)
   at System.Text.RegularExpressions.Regex.Matches(String input, String pattern, RegexOptions options)
   at River.OneMoreAddIn.Commands.SearchAndReplaceEditor.SearchAndReplace(XElement element)
   at River.OneMoreAddIn.Commands.SearchAndReplaceEditor.SearchAndReplace(Page page)
   at River.OneMoreAddIn.Commands.SearchAndReplaceCommand.<Execute>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at River.OneMoreAddIn.CommandFactory.<Run>d__6.MoveNext()
TargetSite: [System] System.Text.RegularExpressions.RegexParser::ScanRegex()

**Comment by stevencohn** [comment]
Yes, search and replace *always* uses regex to simplify the logic. The plus-sign quantifier was absent from the escaped control character list. Fix and will be available in the next release.
