### ISSUE TITLE
Analyze storage out of memory error

### ISSUE THREAD

**Issue by julie777** [stevencohn/OneMore#607]
**Describe the bug**
When I use analyze storage and select the option to include all pages in the notebook, or pages in the current section if fails with an out of memory error.

This wasn't happening previously. I installed 5.0.0 today.

**To Reproduce**
1. select analyze data storage from OneMore/Extras
2. select one of the "include page details" options

![image](https://user-images.githubusercontent.com/5090005/190917412-8060cb8d-f8e6-4b3b-82c2-d4ea6967c324.png)

Note: that the error occurs immediately. I tried to watch memory in the task manager, but it doesn't even register before the error happens.

I rolled back to OneMore 4.19 and it had the same problem. I did manage to find a small notebook (29Mb) that works if I select "include page details for current section"  (496KB) but it fails if I select "include page details for current notebook".

I jumped back to 4.17 and the problem is still there. It works on the very small notebook and section, but fails on pages for all sections. Now I am not sure if I have ever seen that work.

**Expected behavior**
It should succeed without errors.

**Screenshots**

**Environment (if applicable):**
 - OneNote Version: O365
 - OneMore Version: 5.0.0 64bit

**Additional context**
30336:1] Error running command AnalyzeCommand
30336:1] System.OutOfMemoryException
Message: Out of memory.
Source: System.Drawing
StackTrace:    at System.Drawing.Image.GetThumbnailImage(Int32 thumbWidth, Int32 thumbHeight, GetThumbnailImageAbort callback, IntPtr callbackData)
   at River.OneMoreAddIn.Commands.AnalyzeCommand.ReportImage(Table detail, XElement image, Boolean printout)
   at River.OneMoreAddIn.Commands.AnalyzeCommand.ReportPage(Table table, String pageId)
   at River.OneMoreAddIn.Commands.AnalyzeCommand.ReportPages(XElement container, XElement section, String folderPath, String skipId)
   at River.OneMoreAddIn.Commands.AnalyzeCommand.ReportAllPages(XElement container, XElement folder, String folderPath, String skipId)
   at River.OneMoreAddIn.Commands.AnalyzeCommand.<Execute>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at River.OneMoreAddIn.CommandFactory.<Run>d__6.MoveNext()
TargetSite: [System.Drawing] System.Drawing.Image::GetThumbnailImage()

**Comment by stevencohn** [comment]
I was able to reproduce this with a 750MB notebook, so it is certainly real. I'll fix it asap.
