### ISSUE TITLE
Insert code block with text selected yields an error

### ISSUE THREAD

**Issue by maphew** [stevencohn/OneMore#646]
**Describe the bug**
Insert code block with text selected yields an error.

If no text is selected a blank code block is inserted, without an error.

**To Reproduce**
1. select text
2. press `F6` or use menu _Snippets >> Code block_

**Expected behavior**
Selected text will be inserted into a code block.

**Screenshots**
![image](https://user-images.githubusercontent.com/486200/193681149-d4633ef3-29ee-459e-b981-b1197fc2b83d.png)

![image](https://user-images.githubusercontent.com/486200/193681674-439996ff-3e70-4023-b1e0-e3b1cf1af97b.png)

**Environment (if applicable):**
 - OneNote Version: Office 16, desktop, 32 bit
 - OneMore Version: 5.1.2

**Additional context**

Logile:
```
15628:33] Log restarted
15628:33] Running command AboutCommand
15628:33] OnBeginShutdown(custom[])
15628:33] ..shutting down UI
15628:33] ..OnDisconnection(RemoveMode:ext_dm_HostShutdown,custom:[])
15628:33] ..disposing 23 streams
15628:33] ..closing log

10844:1] Starting dllhost 10844, CPU=2401Mhz, en-US/en-US, v5.1.2, OneNote 15.0, Office 16.0
10844:1] ..C:\Program Files (x86)\Microsoft Office\Office16\ONENOTE.EXE (16.0.5014.1000)
10844:1] ..OnConnection(ConnectionMode:ext_cm_Startup,custom[1:Int32])
10844:1] ..OneAddInsUpdate(custom[])
10844:1] ..building ribbon
10844:1] ..building ribbon colorizer commands
10844:1] ..building ribbon language proofing commands
10844:1] ..building ribbon groups
10844:1] ..OnStartupComplete(custom[])
10844:4] ..defining 45 hotkeys for input locale 4105
10844:1] ..starting command service
10844:1] ..starting reminder service
10844:1] ..ready
10844:5] Running command UpdateCommand
10844:6] Running command InsertCodeBlockCommand
10844:6] Error running command InsertCodeBlockCommand
10844:6] System.NullReferenceException
Message: Object reference not set to an instance of an object.
Source: River.OneMoreAddIn
StackTrace:    at River.OneMoreAddIn.Commands.InsertCodeBlockCommand.CalculateWidth(XElement cursor)
   at River.OneMoreAddIn.Commands.InsertCodeBlockCommand.<Execute>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at River.OneMoreAddIn.CommandFactory.<Run>d__6.MoveNext()
TargetSite: [River.OneMoreAddIn] River.OneMoreAddIn.Commands.InsertCodeBlockCommand::CalculateWidth()
```

**Comment by stevencohn** [comment]
Apologies, I hate when I break working functionality

**Comment by maphew** [comment]
> Apologies, I hate when I break working functionality

don't we all!! :)
