### ISSUE TITLE
Convert Text to Table with tab delimiters is broken

### ISSUE THREAD

**Issue by mschiffrin** [stevencohn/OneMore#820]
**Describe the bug**
Convert Text to Table, using tab delimiters, at least some data gets exception

**To Reproduce**
Steps to reproduce the behavior (similar to #311)

1.   In Notepad type e.g. 3 lines of text, using tab where these samples have \t. First line, "abcd\te\tfg"; second line "1\t234\5"; third line "67890\t1\t2"
2.   Select-all, copy to clipboard, paste into OneNote
3.   In OneNote select the pasted 3 lines
4.   Click OneMore -> Table -> Convert Text to Table
5.   Use the now correctly defaulted "Tabs" separator.
6. Click OK
7. Get OneMore error dialog "Error running command TextToTableCommand. See log file for details"

**Expected behavior**
Table ;-)

**Screenshots**
Not screenshot, but log file has:
```
20556:22] System.Xml.XmlException
Message: Reference to undeclared entity 'nbsp'. Line 1, position 9.
Source: System.Xml
StackTrace:    at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.HandleGeneralEntityReference(String name, Boolean isInAttributeValue, Boolean pushFakeEntityIfNullResolver, Int32 entityStartLinePos)
   at System.Xml.XmlTextReaderImpl.HandleEntityReference(Boolean isInAttributeValue, EntityExpandType expandType, Int32& charRefEndPos)
   at System.Xml.XmlTextReaderImpl.ParseText(Int32& startPos, Int32& endPos, Int32& outOrChars)
   at System.Xml.XmlTextReaderImpl.FinishPartialValue()
   at System.Xml.XmlTextReaderImpl.get_Value()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XElement.ReadElementFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XElement.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XElement.Parse(String text, LoadOptions options)
   at System.Xml.Linq.XElement.Parse(String text)
   at River.OneMoreAddIn.Commands.TextToTableCommand.SmartSplit(String xml, String delimeter)
   at River.OneMoreAddIn.Commands.TextToTableCommand.TextToTable(XNamespace ns, List`1 selections)
   at River.OneMoreAddIn.Commands.TextToTableCommand.<Execute>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at River.OneMoreAddIn.CommandFactory.<Run>d__5.MoveNext()
TargetSite: [System.Xml] System.Xml.XmlTextReaderImpl::Throw()
```

**Environment (if applicable):**
 - OneNote Version: Office 2019 Professional Plus. Product Information shows "Version 2210 (Build 15726.20262 Click-to-Run)". About OneNote from there shows "Microsoft OneNote 2016 MSO (Version 2210 Build 16.0.15726.20188) 32-bit"
 - OneMore Version 5.4.3

**Additional context**
This is in OneMore "Show XML", see the nbsp's in a different context from when #311 created.
```
<one:Page xmlns:one="http://schemas.microsoft.com/office/onenote/2013/onenote" ID="{D0716141-5538-44B2-8F0A-BBB7EEE4AD68}{1}{E1949767153990868142591932924699481331340021}" name="abcd e fg" dateTime="2023-01-17T19:53:56.000Z" lastModifiedTime="2023-01-17T19:54:11.000Z" pageLevel="1" isCurrentlyViewed="true" selected="partial" lang="en-US">
  <one:QuickStyleDef index="0" name="PageTitle" fontColor="automatic" highlightColor="automatic" font="Calibri Light" fontSize="20.0" spaceBefore="0.0" spaceAfter="0.0" />
  <one:QuickStyleDef index="1" name="p" fontColor="automatic" highlightColor="automatic" font="Calibri" fontSize="11.0" spaceBefore="0.0" spaceAfter="0.0" />
  <one:PageSettings RTL="false" color="automatic">
    <one:PageSize>
      <one:Automatic />
    </one:PageSize>
    <one:RuleLines visible="false" />
  </one:PageSettings>
  <one:Title lang="en-US">
    <one:OE alignment="left" quickStyleIndex="0">
      <one:T><![CDATA[]]></one:T>
    </one:OE>
  </one:Title>
  <one:Outline selected="partial">
    <one:Position x="36.0" y="86.4000015258789" z="0" />
    <one:Size width="120.2846374511719" height="40.28314971923828" />
    <one:OEChildren selected="partial">
      <one:OE alignment="left" quickStyleIndex="1" selected="partial">
        <one:T selected="all"><![CDATA[]]></one:T>
        <one:T><![CDATA[abcd&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;e&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;fg]]></one:T>
      </one:OE>
      <one:OE alignment="left" quickStyleIndex="1">
        <one:T><![CDATA[1&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;234&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;5]]></one:T>
      </one:OE>
      <one:OE alignment="left" quickStyleIndex="1">
        <one:T><![CDATA[67890&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2]]></one:T>
      </one:OE>
    </one:OEChildren>
  </one:Outline>
</one:Page>
```

**Comment by mschiffrin** [comment]
No apology necessary! I don't think it was a OneMore change that broke it - I think a One**Note** update broke it. I was the one who had logged #311, and it definitely worked for me after you put in #312. 

It's one of my most used OneMore features, I paste in query results from SQL Server Manager, which comes in tab-delimited and can optionally include a header row. Started getting error sometime in last few weeks. I ignored it first few times, partly thinking it might've been data-specific, and partly just not being a good moment to write up reproducible case.

As a workaround I usually just create an Outlook email, paste the data into that, convert to table there, then copy / paste into OneNote.

Thanks!
