### ISSUE TITLE
Calendar throws an exception immediately you click on & doesn't render,

### ISSUE THREAD

**Issue by jasonjac2** [stevencohn/OneMore#912]
# Problem to Solve
Calendar throws an exception immediately you click on & doesn't render, but then I close it and it renders OK

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at OneMoreCalendar.MonthView.PaintGrid(PaintEventArgs e)
   at OneMoreCalendar.MonthView.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.UserControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

From Cal Log:
01| Starting OneMoreCalendar
01| The object does not exist, retyring in 250ms
01| The object does not exist, retyring in 500ms
01| The object does not exist, retyring in 750ms

# Expected Behavior

# Screenshots

# Environment (if applicable)

V5.7.1

# Additional Context

Add any other context about the problem here. Attach page XML file or the app log file as appropriate. You can find the log file here: %localappdata%\temp\OneMore.log

THE FINE PRINT This is a hobby project that I started for myself. I'm happy to take requests and will promise to
consider each one carefully but offer no guarantees that I will ultimately agree to their
usefulness or have time to implement any of them. If OneNote offers a "close enough" work-around
then I will probably reject the request - you've been warned!

**Comment by jasonjac2** [comment]
Closed ON, re-opened and it re-opened cal, and it worked, so must be some artifact of upgrading?

**Comment by jasonjac2** [comment]
cal Log file now empty
